spring.application.name=drakkar-erp

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.flyway.enabled=true
spring.jackson.default-property-inclusion=non_null

server.error.include-message=never

management.endpoints.web.exposure.include=health,info,metrics

info.app.name=Drakkar ERP Soft prototype
info.app.architecture=modular-monolith

drakkar.provisioning-key=${PROVISIONING_KEY}
